### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by xMrAfonso** [jensjeflensje/websk#22]
I think redirects are missing, an example would be, if we are checking for a path of `/discord/`, we should be able to redirect users to another link, like a discord invite, or even another page on our website.

**Comment by jensjeflensje** [comment]
Thank you for your issue!
(You are able to do this with a Location header. See [this](https://github.com/jensjeflensje/websk/blob/main/src/main/java/dev/jensderuiter/websk/skript/expression/NewHeader.java)
