### ISSUE TITLE
User preferences

### ISSUE THREAD

**Issue by xMrAfonso** [jensjeflensje/websk#23]
Unsure if it's doable as a backend, but we should be able to get user preferences like dark or light theme, or even language of the system/browser. These things are possible with other languages.

**Comment by jensjeflensje** [comment]
These are also possible with WebSK. You can set session variables for these things, or local storage via javascript, or you can even add a database into the mix.

**Comment by xMrAfonso** [comment]
As said, I want to get the browsers default theme. Not be able to set one using sessions.
Browsers have default themes that users can choose.s

**Comment by Norbiros** [comment]
Hello,
Sorry that you must wait such a long time :(

**Browser default theme**
U have two ways to do that. One is in CSS another in Java Script

Css:
`@media (prefers-color-scheme: dark) {}`
Tutorial: https://css-tricks.com/dark-modes-with-css/

Java Script:
`if(window.matchMedia('(prefers-color-scheme: dark)').matches){}`
Tutorial: https://stackoverflow.com/questions/56393880/how-do-i-detect-dark-mode-using-javascript

**Browser language**
To get language you need to look to headers of http request. This thing is not implemented yet, but i'm working on it :) 

_Goodbye and wait for next update!_
_PS: And next time, look at https://google.com_

**Comment by xMrAfonso** [comment]
I already knew about those…. I am not new to html and css…. I asked for an option, that’s all.

**Comment by Norbiros** [comment]
Hi again,
Do u think about something like `page's default theme`? It is supposed to be in our html template system, or in skript?

`So why u didn't send that? It can save a lot of time :) `

**Comment by ItsTheSky** [comment]
HI!
This manage the user's end page, and therefore don't ave anything related to Websk.
However, you can still save and restore theme configured for each IP in your Script in variable or YAML, then apply the page you want for it later.
There's a lot of easy way in JavaScript to manage cookies, feel free to even make your own API using Websk to receive JavaScript's request for changing theme.

**Comment by Norbiros** [comment]
I created PR that adds option to get header!
**Now you can check default language of browser!**
