### ISSUE TITLE
Small Ideas

### ISSUE THREAD

**Issue by Norbiros** [jensjeflensje/websk#27]
Add something like that:
`request method` and `request ip`
Becouse now we can use
`method of request`

**Comment by ItsTheSky** [comment]
Not sure what will be ued with, could you give complete example code for these please?

**Comment by Norbiros** [comment]
Only easier way of doing that. For example when i look at skript and i found **ip** i tried `request ip`... IDK it is me, or a lot of skripters will do the same as me... 
Code **Not tested**:
```
    Skript.registerExpression(
        ExprRequestMethod.class,
        String.class,
        ExpressionType.SIMPLE,
        "%request% method",
        "method of %request%",
        "%request%'s method"
    );

**Comment by Norbiros** [comment]
It is stupid addition. Only I see problem with this, maybe becouse that I'm Polish so I took it from Polish grammar... 
Sorry for problem.
