### ISSUE TITLE
Better template system

### ISSUE THREAD

**Issue by Norbiros** [jensjeflensje/websk#41]
Hello!
Now we have great template system, but it can be better!
These are examples things that we can add:
`{% extends "base.html" %}` - this function override template `base.html`. 
`{% block "content" %}` - this create block, that can have content of other file using extends
`{{ block.super }}` - when you write after this, you add code to previous block, not replace it
`{{ value|filter }}` - filter can be for example `lenght`, `default`
Ideas are from https://docs.djangoproject.com/en/4.0/ref/templates/language/.

**Comment by ItsTheSky** [comment]
I'm gonna start working on it if you want.
I'll make a draft PR and use your comment to keep a trace of what you wanted.
Feel free to ask / post review about the current way of this features :p
