### ISSUE TITLE
can I use css

### ISSUE THREAD

**Issue by UnderCurve** [jensjeflensje/websk#44]
I'm trying to make a website with websk but my CSS won't work

What it looks like: ![image](https://user-images.githubusercontent.com/85709030/159784390-04fb00b1-3214-4663-ad42-5d06af4a8c65.png)
What it should look like: ![image](https://user-images.githubusercontent.com/85709030/159784546-088e0025-f7cf-4994-a905-54e8517698a1.png)

**Comment by Norbiros** [comment]
Hello!
Why this issue is closed?
Can I help you with something, or you fixed it by yourself? @UnderCurve
