### ISSUE TITLE
How to upload a file? like a images to server

### ISSUE THREAD

**Issue by LowScarlet** [jensjeflensje/websk#46]

**Comment by Norbiros** [comment]
You can do this in 2 ways:
1. Use newest version from nightly (github actions) and then add your file to `websk/files` and just navigate to this file in HTML 
2. Use latest release and in Skript write:
 ```
if event-path is "file.PNG"
  return file.PNG
```
Or something like that... And in HTML write just `file.png|

**Comment by Norbiros** [comment]
Can you close this? Do you have any more questions?

**Comment by Norbiros** [comment]
@SkyCraft78 can you close this issue?
